# tests/test_integration.py
import contextlib
import json
import sys
from pathlib import Path

from src.main import main


def test_pipeline_end_to_end(test_pipeline_dir):
    """Executes the full pipeline end-to-end in-process (matching CLI arguments and 
    stderr redirection to /tmp/memory_profile.log) without mocking or subprocesses, 
    ensuring 100% test coverage and rigorous artifact verification.
    """
    input_file_name = "input.json"
    output_file_name = "output.json"
    log_file_path = Path("/tmp/memory_profile.log")

    # Construct the exact CLI argument structure requested
    test_args = [
        "src/main.py",
        "--input_output_folder",
        str(test_pipeline_dir),
        "--input_file_name",
        input_file_name,
        "--output_file_name",
        output_file_name,
    ]

    # Simulate CLI invocation in-process while redirecting stderr to /tmp/memory_profile.log
    original_argv = sys.argv
    sys.argv = test_args

    log_file_path.parent.mkdir(parents=True, exist_ok=True)
    with open(log_file_path, "w") as log_file:
        with contextlib.redirect_stderr(log_file):
            try:
                main()
            finally:
                sys.argv = original_argv

    # 1. Verify output JSON payload exists and reflects complete success
    output_json_path = test_pipeline_dir / output_file_name
    assert output_json_path.exists(), "output.json was not generated by the pipeline."

    with open(output_json_path, "r") as f:
        output_data = json.load(f)

    # Validate state structure & execution outcome
    results = output_data.get("results", {})
    assert results.get("status") == "success", f"Pipeline status failed: {results}"
    assert results.get("error") == "", f"Pipeline error message present: {results.get('error')}"
    assert "date_time" in results, "Execution timestamp 'date_time' missing from results."

    # Validate inputs and config preservation
    assert "inputs" in output_data, "Output payload missing 'inputs'."
    assert "config" in output_data, "Output payload missing 'config'."
    assert output_data["inputs"].get("fps") == 30, "Configured frame rate mismatch."

    # 2. Verify frames loader module execution (frames directory and extraction)
    frames_dir = test_pipeline_dir / "frames"
    assert frames_dir.exists(), "Frames directory was not created."
    extracted_frames = list(frames_dir.rglob("*.jpg")) + list(frames_dir.rglob("*.png"))
    assert len(extracted_frames) > 0, "Frames loader failed to extract any frames into target directory."

    # 3. Verify video assembler module execution (MP4 generation & non-zero file size)
    video_path = Path(output_data["inputs"]["output_video_path"])
    assert video_path.exists(), "Output MP4 video file was not compiled."
    assert video_path.stat().st_size > 0, "Compiled output video file is empty."

    # 4. Verify stderr logging / memory profile log capture
    assert log_file_path.exists(), "Memory profile log file was not written to /tmp/memory_profile.log."
    log_content = log_file_path.read_text()
    assert len(log_content) > 0, "Memory profile log file is empty."
    assert "Pipeline execution completed successfully" in log_content, "Expected success log message missing."
